version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_NAME: cinema
      DB_USER: postgres
      DB_PASSWORD: senha123
      DB_HOST: db
    depends_on:
      - db